// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metadata returned by `fs/getMetadata`.
 */
export type FsGetMetadataResponse = { 
/**
 * Whether the path currently resolves to a directory.
 */
isDirectory: boolean, 
/**
 * Whether the path currently resolves to a regular file.
 */
isFile: boolean, 
/**
 * File creation time in Unix milliseconds when available, otherwise `0`.
 */
createdAtMs: number, 
/**
 * File modification time in Unix milliseconds when available, otherwise `0`.
 */
modifiedAtMs: number, };
