// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";

/**
 * Created watch handle returned by `fs/watch`.
 */
export type FsWatchResponse = { 
/**
 * Connection-scoped watch identifier used for `fs/unwatch` and `fs/changed`.
 */
watchId: string, 
/**
 * Canonicalized path associated with the watch.
 */
path: AbsolutePathBuf, };
