// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * [UNSTABLE] Lifecycle state for a guardian approval review.
 */
export type GuardianApprovalReviewStatus = "inProgress" | "approved" | "denied" | "aborted";
