// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LoginAccountParams = { "type": "apiKey", apiKey: string, } | { "type": "chatgpt" } | { "type": "chatgptAuthTokens", 
/**
 * ID token (JWT) supplied by the client.
 *
 * This token is used for identity and account metadata (email, plan type,
 * workspace id).
 */
idToken: string, 
/**
 * Access token (JWT) supplied by the client.
 * This token is used for backend API requests.
 */
accessToken: string, };
