// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PluginUninstallParams = { pluginId: string, 
/**
 * When true, apply the remote plugin change before the local uninstall flow.
 */
forceRemoteSync?: boolean, };
