name: 🪲 Other Bug
description: Report an issue in Codex Web, integrations, or other Codex components
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Before submitting a new issue, please search for existing issues to see if your issue has already been reported.
        If it has, please add a 👍 reaction (no need to leave a comment) to the existing issue instead of creating a new one.

        If you need help or support using Codex and are not reporting a bug, please post on [codex/discussions](https://github.com/openai/codex/discussions), where you can ask questions or engage with others on ideas for how to improve codex.

  - type: textarea
    id: actual
    attributes:
      label: What issue are you seeing?
      description: Please include the full error messages and prompts with PII redacted. If possible, please provide text instead of a screenshot.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: What steps can reproduce the bug?
      description: Explain the bug and provide a code snippet that can reproduce it.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What is the expected behavior?
      description: If possible, please provide text instead of a screenshot.
  - type: textarea
    id: notes
    attributes:
      label: Additional information
      description: Is there anything else you think we should know?
