// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentStatus } from "./AgentStatus";
import type { ReasoningEffort } from "./ReasoningEffort";
import type { ThreadId } from "./ThreadId";

export type CollabAgentSpawnEndEvent = { 
/**
 * Identifier for the collab tool call.
 */
call_id: string, 
/**
 * Thread ID of the sender.
 */
sender_thread_id: ThreadId, 
/**
 * Thread ID of the newly spawned agent, if it was created.
 */
new_thread_id: ThreadId | null, 
/**
 * Optional nickname assigned to the new agent.
 */
new_agent_nickname?: string | null, 
/**
 * Optional role assigned to the new agent.
 */
new_agent_role?: string | null, 
/**
 * Initial prompt sent to the agent. Can be empty to prevent CoT leaking at the
 * beginning.
 */
prompt: string, 
/**
 * Model requested for the spawned agent.
 */
model: string, 
/**
 * Reasoning effort requested for the spawned agent.
 */
reasoning_effort: ReasoningEffort, 
/**
 * Last known status of the new agent reported to the sender agent.
 */
status: AgentStatus, };
