// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DynamicToolCallOutputContentItem } from "./DynamicToolCallOutputContentItem";
import type { JsonValue } from "./serde_json/JsonValue";

export type DynamicToolCallResponseEvent = { 
/**
 * Identifier for the corresponding DynamicToolCallRequest.
 */
call_id: string, 
/**
 * Turn ID that this dynamic tool call belongs to.
 */
turn_id: string, 
/**
 * Dynamic tool name.
 */
tool: string, 
/**
 * Dynamic tool call arguments.
 */
arguments: JsonValue, 
/**
 * Dynamic tool response content items.
 */
content_items: Array<DynamicToolCallOutputContentItem>, 
/**
 * Whether the tool call succeeded.
 */
success: boolean, 
/**
 * Optional error text when the tool call failed before producing a response.
 */
error: string | null, 
/**
 * The duration of the dynamic tool call.
 */
duration: string, };
