// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElicitationRequest } from "./ElicitationRequest";

export type ElicitationRequestEvent = { 
/**
 * Turn ID that this elicitation belongs to, when known.
 */
turn_id?: string, server_name: string, id: string | number, request: ElicitationRequest, };
