// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RejectConfig = { 
/**
 * Reject approval prompts related to sandbox escalation.
 */
sandbox_approval: boolean, 
/**
 * Reject prompts triggered by execpolicy `prompt` rules.
 */
rules: boolean, 
/**
 * Reject MCP elicitation prompts.
 */
mcp_elicitations: boolean, };
